kind: pipeline
type: docker
name: default

trigger:
  branch:
  - master
  - test-ci
  - develop

pipeline:
  # test:
  #   image: node
  #   commands:
      # - npm i
      # - npm run test

  publish-ui:
    image: plugins/docker
    dockerfile: ./Dockerfile
    context: .
    repo: gravityhuborg/gravity-explorer-ui
    tags: [latest, v2]
    secrets: [ docker_username, docker_password ]

  test-deployment:
    image: gravityhuborg/gravity-explorer-ui
    secrets: []
    bash: "rebuild.sh"