/**
 * Gravity Node API.
 * the purpose of this application is to provide an application that is using plain go code to define an API
 *
 * OpenAPI spec version: 1.0
 * Contact: shamil@venlab.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Nebula { 
    /**
     * the address of the nebula SC
     */
    address: string;
    /**
     * the description of the nebula
     */
    description: string;
    /**
     * the name of the nebula
     */
    name: string;
    /**
     * Actual pointers
     */
    nodesUsing?: Array<string>;
    /**
     * Data feed subscription charge regularity Represents minutes. For i.g. 1440 - one day
     */
    regularity: number;
    /**
     * the score of the nebula
     */
    score: number;
    /**
     * the status of the nebula
     */
    status: number;
    subscriptionFee?: string;
    /**
     * the target chain of the nebula recently allowed: WAVES, ETH
     */
    targetChain: number;
}