/**
 * Gravity Node API.
 * the purpose of this application is to provide an application that is using plain go code to define an API
 *
 * OpenAPI spec version: 1.0
 * Contact: shamil@venlab.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Nebula } from './nebula';
import { NodeContacts } from './nodeContacts';
import { NodeSocials } from './nodeSocials';

export interface Node { 
    contacts?: NodeContacts;
    depositAmount?: number;
    depositChain?: number;
    description?: string;
    joinedAt?: number;
    lockedUntil?: number;
    name?: string;
    nebulasUsing?: Array<Nebula>;
    score?: number;
    socials?: NodeSocials;
}