/**
 * Gravity Node API.
 * the purpose of this application is to provide an application that is using plain go code to define an API
 *
 * OpenAPI spec version: 1.0
 * Contact: shamil@venlab.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface NodeSocials { 
    fb?: string;
    linkedin?: string;
    tg?: string;
    twitter?: string;
}