/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */
import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';
import { SubTypeFactory } from './sub-type-factory';


export interface INodeSocials {
    fb?: string;
    linkedin?: string;
    tg?: string;
    twitter?: string;
}


export class NodeSocials extends BaseModel implements INodeSocials  {

    static FB_FIELD_NAME = 'fb';
    static LINKEDIN_FIELD_NAME = 'linkedin';
    static TG_FIELD_NAME = 'tg';
    static TWITTER_FIELD_NAME = 'twitter';

    fb: string;
    linkedin: string;
    tg: string;
    twitter: string;

    /**
     * constructor
     * @param values Can be used to set a webapi response or formValues to this newly constructed model
    * @useFormGroupValuesToModel if true use formValues
    */
    constructor(values?: Partial<INodeSocials>, useFormGroupValuesToModel = false) {
        super();

        if (values) {
            this.setValues(values, useFormGroupValuesToModel);
        }
    }

    /**
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: Partial<INodeSocials>, useFormGroupValuesToModel = false): void {
        if (values) {
            const rawValues = this.getValuesToUse(values, useFormGroupValuesToModel);
            this.fb = this.getValue<string>(rawValues, NodeSocials.FB_FIELD_NAME);
            this.linkedin = this.getValue<string>(rawValues, NodeSocials.LINKEDIN_FIELD_NAME);
            this.tg = this.getValue<string>(rawValues, NodeSocials.TG_FIELD_NAME);
            this.twitter = this.getValue<string>(rawValues, NodeSocials.TWITTER_FIELD_NAME);
            // set values in model properties for added formControls
            super.setValuesInAddedPropertiesOfAttachedFormControls(values, useFormGroupValuesToModel);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                fb: new FormControl(this.fb),
                linkedin: new FormControl(this.linkedin),
                tg: new FormControl(this.tg),
                twitter: new FormControl(this.twitter),
            });
        }
        return this._formGroup;
    }

    /**
     * set the FormGroup values to the model values.
    */
    setFormGroupValues() {
        this.$formGroup.controls[NodeSocials.FB_FIELD_NAME].setValue(this.fb);
        this.$formGroup.controls[NodeSocials.LINKEDIN_FIELD_NAME].setValue(this.linkedin);
        this.$formGroup.controls[NodeSocials.TG_FIELD_NAME].setValue(this.tg);
        this.$formGroup.controls[NodeSocials.TWITTER_FIELD_NAME].setValue(this.twitter);
        // set formValues in added formControls
        super.setFormGroupValuesInAddedFormControls();
    }
}
